import { defineStore } from "pinia";
import { QTableProps } from "quasar";
import {
  IstoreProfile,
  IcountAllStore,
  IdetailsListData,
  IProviderCircuit,
  ImindanaoStoreCounts,
  IproviderCircuitsTodayCounts,
  Icliqq,
  rowsLog,
  DownCircuits,
  ICircuitLoops,
} from "src/api/types";

export const useSiteStore = defineStore("sites", {
  state: () => ({
    clientIp: "",
    logsRows: [] as rowsLog[],
    logUsers: [] as string[],
    storeInfo: {} as IstoreProfile,
    storeSummaryRow: [] as IProviderCircuit[],
    storeCircuitRow: [] as ICircuitLoops[],
    downCircuits: [] as DownCircuits[],
    storeCounts: {} as IcountAllStore,
    storeMindanaoCounts: {} as ImindanaoStoreCounts,
    providerCircuitsTodayCount: {} as IproviderCircuitsTodayCounts,
    authToken: "",
    logDate: {
      from: "",
      to: "",
    },

    cliqqDetails: {
      dateRange: {
        from: "",
        to: "",
      },
      cliqqRow: [] as Icliqq[],
    },
    downStoresRow: [],
    midanaoStoresRow: [],
    countsLoaded: false,
    selectedStoreId: "",
    storeSummaryColumn: [
      {
        name: "site_id",
        align: "left",
        label: "Site ID",
        field: "site_id",
        sortable: true,
        sort: (a, b) => parseInt(a, 10) - parseInt(b, 10),
      },
      {
        name: "store_description",
        align: "left",
        label: "Store Name",
        field: "store_description",
        sortable: true,
      },
      {
        name: "loopback_0",
        align: "left",
        label: "Store (7days) Down Duration",
        field: (row) => row.loopback_0,
        sortable: true,
      },
      {
        name: "loopback_1",
        align: "left",
        label: "Primary (7days) Down Duration",
        field: (row) => row.loopback_1,
        sortable: true,
      },
      {
        name: "loopback_2",
        align: "left",
        label: "Backup (7days) Down Duration",
        field: (row) => row.loopback_2,
        sortable: true,
      },
      {
        name: "loopback_0_24h",
        align: "left",
        label: "Store (24hrs) Down Duration",
        field: (row) => row.loopback_0_24h,
        sortable: true,
      },
      {
        name: "loopback_1_24h",
        align: "left",
        label: "Primary (24hrs) Down Duration",
        field: (row) => row.loopback_1_24h,
        sortable: true,
      },
      {
        name: "loopback_2_24h",
        align: "left",
        label: "Backup (24hrs) Down Duration",
        field: (row) => row.loopback_2_24h,
        sortable: true,
      },
      {
        name: "zabbix_down_duration",
        align: "left",
        label: "Down Duration",
        field: "zabbix_down_duration",
        sortable: true,
      },
      {
        name: "prometheus_down_duration",
        align: "left",
        label: "Down Duration",
        field: "prometheus_down_duration",
        sortable: true,
      },
      {
        name: "primary_provider",
        align: "left",
        label: "Primary Circuit Provider",
        field: "primary_provider",
        sortable: true,
      },
      {
        name: "last_change_primary",
        align: "left",
        label: "Primary Last Updated",
        field: "last_change_primary",
        sortable: true,
      },

      // {
      //   name: "primary_circuit_status",
      //   align: "left",
      //   label: "Primary Circuit Status",
      //   field: "primary_circuit_status",
      //   sortable: true,
      // },
      {
        name: "backup_provider",
        align: "left",
        label: "Backup Circuit Provider",
        field: "backup_provider",
        sortable: true,
      },
      {
        name: "last_change_backup",
        align: "left",
        label: "Backup Last Updated",
        field: "last_change_backup",
        sortable: true,
      },
      {
        name: "region",
        align: "left",
        label: "Region",
        field: "region",
        sortable: true,
      },
      {
        name: "city",
        align: "left",
        label: "City",
        field: "city",
        sortable: true,
      },
      {
        name: "province",
        align: "left",
        label: "Province",
        field: "province",
        sortable: true,
      },
      {
        name: "latitude",
        align: "left",
        label: "Latitude",
        field: "latitude",
        sortable: true,
      },
      {
        name: "longitude",
        align: "left",
        label: "Longitude",
        field: "latitude",
        sortable: true,
      },
      // {
      //   name: "backup_circuit_status",
      //   align: "left",
      //   label: "Backup Circuit Status",
      //   field: "backup_circuit_status",
      //   sortable: true,
      // },
    ] as QTableProps["columns"],

    storeProviderCircuit: [
      {
        name: "site_id",
        align: "left",
        label: "Site ID",
        field: "site_id",
        sortable: true,
      },
      {
        name: "router",
        align: "left",
        label: "Router",
        field: "router",
        sortable: true,
      },
      {
        name: "loopback_0",
        align: "left",
        label: "Store (7days)",
        field: (row) => row.loopback_0,
        sortable: true,
      },
      {
        name: "loopback_1",
        align: "left",
        label: "Primary (7days)",
        field: (row) => row.loopback_1,

        sortable: true,
      },
      {
        name: "loopback_2",
        align: "left",
        label: "Backup (7days)",
        field: (row) => row.loopback_2,

        sortable: true,
      },
      // {
      //   name: "loopback_3",
      //   align: "left",
      //   label: "Third Circuit (7days)",
      //   field: (row) => row.loopback_3,
      //   sortable: true,
      // },
      {
        name: "loopback_0_24h",
        align: "left",
        label: "Store (24hrs)",
        field: (row) => row.loopback_0_24h,
        sortable: true,
      },
      {
        name: "loopback_1_24h",
        align: "left",
        label: "Primary (24hrs)",
        field: (row) => row.loopback_1_24h,
        sortable: true,
      },
      {
        name: "loopback_2_24h",
        align: "left",
        label: "Backup (24hrs)",
        field: (row) => row.loopback_2_24h,
        sortable: true,
      },
      // {
      //   name: "loopback_3_24h",
      //   align: "left",
      //   label: "Third Circuit (24hrs)",
      //   field: (row) => row.loopback_3_24h,
      //   sortable: true,
      // },
      {
        name: "provider_primary",
        align: "left",
        label: "Primary Circuit Provider",
        field: "provider_primary",
        sortable: true,
      },

      {
        name: "provider_backup",
        align: "left",
        label: "Backup Circuit Provider",
        field: "provider_backup",
        sortable: true,
      },
      // {
      //   name: "provider_third",
      //   align: "left",
      //   label: "Backup Circuit third",
      //   field: "provider_third",
      //   sortable: true,
      // },
      {
        name: "mac_primary",
        align: "left",
        label: "Mac Primary",
        field: "mac_primary",
        sortable: true,
      },
      {
        name: "mac_backup",
        align: "left",
        label: "Mac Backup",
        field: "mac_backup",
        sortable: true,
      },
      // {
      //   name: "mac_third",
      //   align: "left",
      //   label: "Mac Third",
      //   field: "mac_third",
      //   sortable: true,
      // },
      {
        name: "gtw_primary",
        align: "left",
        label: "Gateway Ip Primary",
        field: "gtw_primary",
        sortable: true,
      },
      {
        name: "gtw_backup",
        align: "left",
        label: "Gateway Ip Backup",
        field: "gtw_backup",
        sortable: true,
      },
      // {
      //   name: "gtw_third",
      //   align: "left",
      //   label: "Gateway Ip Third",
      //   field: "gtw_third",
      //   sortable: true,
      // },
      {
        name: "public_ip_primary",
        align: "left",
        label: "Public Ip Primary",
        field: "public_ip_primary",
        sortable: true,
      },
      {
        name: "public_ip_backup",
        align: "left",
        label: "Public Ip Backup",
        field: "public_ip_backup",
        sortable: true,
      },
      // {
      //   name: "public_ip_third",
      //   align: "left",
      //   label: "Public Ip Third",
      //   field: "public_ip_third",
      //   sortable: true,
      // },
      // {
      //   name: "serial_number",
      //   align: "left",
      //   label: "Serial Number",
      //   field: "serial_number",
      //   sortable: true,
      // },
    ] as QTableProps["columns"],
    storeProviderCircuitPSC: [
      {
        name: "site_id",
        align: "left",
        label: "Site ID",
        field: "site_id",
        sortable: true,
      },
      {
        name: "router",
        align: "left",
        label: "Router",
        field: "router",
        sortable: true,
      },
      {
        name: "loopback_0",
        align: "left",
        label: "Store (7days)",
        field: (row) => row.loopback_0,
        sortable: true,
      },
      {
        name: "loopback_1",
        align: "left",
        label: "Primary (7days)",
        field: (row) => row.loopback_1,

        sortable: true,
      },
      {
        name: "loopback_2",
        align: "left",
        label: "Backup (7days)",
        field: (row) => row.loopback_2,

        sortable: true,
      },

      {
        name: "loopback_0_24h",
        align: "left",
        label: "Store (24hrs)",
        field: (row) => row.loopback_0_24h,
        sortable: true,
      },
      {
        name: "loopback_1_24h",
        align: "left",
        label: "Primary (24hrs)",
        field: (row) => row.loopback_1_24h,
        sortable: true,
      },
      {
        name: "loopback_2_24h",
        align: "left",
        label: "Backup (24hrs)",
        field: (row) => row.loopback_2_24h,
        sortable: true,
      },
    ] as QTableProps["columns"],

    storeCircuitLoop: [
      {
        name: "site_id",
        align: "left",
        label: "Site ID",
        field: "site_id",
        sortable: true,
      },
      {
        name: "router",
        align: "left",
        label: "Router",
        field: "router",
        sortable: true,
      },
      {
        name: "loopback_0",
        align: "left",
        label: "Store (7days)",
        field: (row) => row.loopback_0,
        sortable: true,
      },
      {
        name: "loopback_1",
        align: "left",
        label: "Primary (7days)",
        field: (row) => row.loopback_1,

        sortable: true,
      },
      {
        name: "loopback_2",
        align: "left",
        label: "Backup (7days)",
        field: (row) => row.loopback_2,

        sortable: true,
      },
      {
        name: "loopback_0_24h",
        align: "left",
        label: "Store (24hrs)",
        field: (row) => row.loopback_0_24h,
        sortable: true,
      },
      {
        name: "loopback_1_24h",
        align: "left",
        label: "Primary (24hrs)",
        field: (row) => row.loopback_1_24h,
        sortable: true,
      },
      {
        name: "loopback_2_24h",
        align: "left",
        label: "Backup (24hrs)",
        field: (row) => row.loopback_2_24h,
        sortable: true,
      },
      {
        name: "provider_primary",
        align: "left",
        label: "Primary Circuit Provider",
        field: "prov_vpn_1",
        sortable: true,
      },

      {
        name: "provider_backup",
        align: "left",
        label: "Backup Circuit Provider",
        field: "prov_vpn_2",
        sortable: true,
      },
      {
        name: "mac_primary",
        align: "left",
        label: "Mac Primary",
        field: "mac_address_1",
        sortable: true,
      },
      {
        name: "mac_backup",
        align: "left",
        label: "Mac Backup",
        field: "mac_address_2",
        sortable: true,
      },
      {
        name: "gtw_primary",
        align: "left",
        label: "Gateway Ip Primary",
        field: "gateway_ip_1",
        sortable: true,
      },
      {
        name: "gtw_backup",
        align: "left",
        label: "Gateway Ip Backup",
        field: "gateway_ip_2",
        sortable: true,
      },
      {
        name: "public_ip_primary",
        align: "left",
        label: "Public Ip Primary",
        field: "last_discovered_ip1",
        sortable: true,
      },
      {
        name: "public_ip_backup",
        align: "left",
        label: "Public Ip Backup",
        field: "last_discovered_ip2",
        sortable: true,
      },
      {
        name: "serial_number",
        align: "left",
        label: "Serial Number",
        field: "serial_number",
        sortable: true,
      },
    ] as QTableProps["columns"],
    storeCircuitLoopPSC: [
      {
        name: "site_id",
        align: "left",
        label: "Site ID",
        field: "site_id",
        sortable: true,
      },
      {
        name: "router",
        align: "left",
        label: "Router",
        field: "router",
        sortable: true,
      },
      {
        name: "loopback_0",
        align: "left",
        label: "Store (7days)",
        field: (row) => row.loopback_0,
        sortable: true,
      },
      {
        name: "loopback_1",
        align: "left",
        label: "Primary (7days)",
        field: (row) => row.loopback_1,

        sortable: true,
      },
      {
        name: "loopback_2",
        align: "left",
        label: "Backup (7days)",
        field: (row) => row.loopback_2,

        sortable: true,
      },

      {
        name: "loopback_0_24h",
        align: "left",
        label: "Store (24hrs)",
        field: (row) => row.loopback_0_24h,
        sortable: true,
      },
      {
        name: "loopback_1_24h",
        align: "left",
        label: "Primary (24hrs)",
        field: (row) => row.loopback_1_24h,
        sortable: true,
      },
      {
        name: "loopback_2_24h",
        align: "left",
        label: "Backup (24hrs)",
        field: (row) => row.loopback_2_24h,
        sortable: true,
      },
    ] as QTableProps["columns"],
    
  }),
});
